from dashboard.views.home import home
from dashboard.views.notes import notes
from dashboard.views.homework import homework
from dashboard.views.youtube import youtube
from dashboard.views.todo import todo
from dashboard.views.dictionary import dictionary
from dashboard.views.books import books
from dashboard.views.wiki import wiki
from dashboard.views.conversion import conversion
from dashboard.views.register import register
from dashboard.views.profile import profile